image: ubuntu/plucky
sources:
- "https://git.sr.ht/~lukegrahamlandry/franca#3382f941d57b42fab896ec57d269ba337eec7212"
- "https://git.sr.ht/~lukegrahamlandry/rustc_codegen_ferb"
packages:
- "rustup"
tasks:
- test: |
    cd franca
    ./boot/strap.sh -no-test
    cd ../rustc_codegen_ferb
    ./test.sh
