image: ubuntu/plucky
sources:
- "https://git.sr.ht/~lukegrahamlandry/franca#e6830e46f2e85fb705f5f6da2127016f3d0744e6"
- "https://git.sr.ht/~lukegrahamlandry/rustc_codegen_ferb"
packages:
- "rustup"
tasks:
- test: |
    cd franca
    ./boot/strap.sh -no-test
    cd ../rustc_codegen_ferb
    ./test.sh
