image: ubuntu/plucky
sources:
- "https://git.sr.ht/~lukegrahamlandry/franca#b1b282d1688ec71a28f8235b845df9658149f8da"
- "https://git.sr.ht/~lukegrahamlandry/rustc_codegen_ferb"
packages:
- "rustup"
tasks:
- test: |
    cd franca
    ./boot/strap.sh -no-test
    cd ../rustc_codegen_ferb
    ./test.sh
