image: ubuntu/plucky
sources:
- "https://git.sr.ht/~lukegrahamlandry/franca#e9f5119a1a6dd4c40d049545863b7aa5ea922b90"
- "https://git.sr.ht/~lukegrahamlandry/rustc_codegen_ferb"
- "https://github.com/LukeGrahamLandry/roland.git#d061c1076e37594b13444dd6715f7b0f3d402c9d"
packages:
- "rustup"
tasks:
- franca: |
    cd franca
    ./boot/strap.sh -no-test
- test: |
    cd rustc_codegen_ferb
    rustup default stable
    ../franca/target/f.out tests/main.fr -roland
