image: ubuntu/plucky
sources:
- "https://git.sr.ht/~lukegrahamlandry/franca#b1b282d1688ec71a28f8235b845df9658149f8da"
- "https://git.sr.ht/~lukegrahamlandry/rustc_codegen_ferb"
packages:
- "rustup"
tasks:
- franca: |
    cd franca
    ./boot/strap.sh -no-test
- test: |
    cd rustc_codegen_ferb
    ../franca/target/f.out tests/main.fr
